# Generated by Django 2.0.6 on 2019-05-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_friendlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='content',
        ),
    ]
